<div data-layer="Frame 1" className="Frame1" style={{width: 1920, height: 7620, position: 'relative', background: 'white', overflow: 'hidden'}}>
  <div data-layer="Rectangle 4" className="Rectangle4" style={{width: 1920, height: 962, left: 0, top: 6658, position: 'absolute', background: 'black'}} />
  <img data-layer="ChatGPT Image 10 мая 2025 г., 17_50_35 1" className="ChatgptImage1020251750351" style={{width: 962, height: 962, left: 0, top: 6658, position: 'absolute'}} src="https://placehold.co/962x962" />
  <div data-layer="Rectangle 1" className="Rectangle1" style={{width: 31, height: 2070, left: 0, top: 0, position: 'absolute', background: 'black'}} />
  <div data-layer="Rectangle 2" className="Rectangle2" style={{width: 1774, height: 950, left: 73, top: 30, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="михаил образцов" style={{left: 663, top: 1317, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>михаил образцов </div>
  <div data-layer="Дизайн без воплощения — это идея. Я делаю — чтобы работало" style={{width: 1227, height: 154, left: 343, top: 3569, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>Дизайн без воплощения — это идея. <br/>Я делаю — чтобы работало</div>
  <div data-layer="Дизайн без воплощения — это идея. Я делаю — чтобы работало" style={{width: 1227, height: 154, left: 343, top: 6177, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>Дизайн без воплощения — это идея. <br/>Я делаю — чтобы работало</div>
  <div data-layer="хард-скилл" style={{left: 768, top: 3108, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>хард-скилл</div>
  <div data-layer="кейсы" style={{left: 1460, top: 3983, position: 'absolute', textAlign: 'right', color: '#505050', fontSize: 96, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>кейсы</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 603, height: 1150, left: 0, top: 4811, position: 'absolute', background: 'black', border: '1px black solid'}} />
  <div data-layer="Рад знакомству. В коммерческом дизайне с 2008 года. Нет выдуманных компаний, нет макетов для портфолио - только реальные проекты, разработка с нуля до выхода продукта на рынок, последующее сопровождение. Ставлю перед собой основной задачу в успешной реализации бренда или продукта своего партнера." className="2008" style={{width: 1149, height: 151, left: 379, top: 1436, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 32, fontFamily: 'Alumni Sans', fontWeight: '400', wordWrap: 'break-word'}}>Рад знакомству. В коммерческом дизайне с 2008 года. Нет выдуманных компаний, нет макетов для портфолио - только реальные проекты, разработка с нуля до выхода продукта на рынок, последующее сопровождение. <br/><br/>Ставлю перед собой основной задачу в успешной реализации бренда или продукта своего партнера.</div>
  <div data-layer="Реализация творческих амбиций это всегда хорошо, но продукт порой требует практичных решений в рекламе. Вместе с вами, я смогу найти путь к успешной презентации." style={{width: 1149, left: 382, top: 3758, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 32, fontFamily: 'Alumni Sans', fontWeight: '400', wordWrap: 'break-word'}}>Реализация творческих амбиций это всегда хорошо, но продукт порой требует практичных решений в рекламе. Вместе с вами, я смогу найти путь к успешной презентации.</div>
  <div data-layer="Реализация творческих амбиций это всегда хорошо, но продукт порой требует практичных решений в рекламе. Вместе с вами, я смогу найти путь к успешной презентации." style={{width: 1149, left: 382, top: 6366, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 32, fontFamily: 'Alumni Sans', fontWeight: '400', wordWrap: 'break-word'}}>Реализация творческих амбиций это всегда хорошо, но продукт порой требует практичных решений в рекламе. Вместе с вами, я смогу найти путь к успешной презентации.</div>
  <div data-layer="растр/ретушь" style={{left: 147, top: 3233, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>растр/ретушь</div>
  <div data-layer="photoshop" className="Photoshop" style={{left: 147, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>photoshop</div>
  <div data-layer="Illustrator" className="Illustrator" style={{left: 451, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>Illustrator</div>
  <div data-layer="Figma" className="Figma" style={{left: 682, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>Figma</div>
  <div data-layer="InDesign" className="Indesign" style={{left: 940, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>InDesign</div>
  <div data-layer="Acrobat Distiler" className="AcrobatDistiler" style={{width: 146, height: 59, left: 1182, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>Acrobat<br/>Distiler</div>
  <div data-layer="artificial intelligence" className="ArtificialIntelligence" style={{width: 146, height: 59, left: 1452, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>artificial intelligence</div>
  <div data-layer="html Css" className="HtmlCss" style={{left: 1674, top: 3272, position: 'absolute', color: '#AAAAAA', fontSize: 24, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>html<br/>Css</div>
  <div data-layer="вектор" style={{left: 451, top: 3233, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>вектор</div>
  <div data-layer="прототип" style={{left: 683, top: 3233, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>прототип</div>
  <div data-layer="верстка" style={{left: 940, top: 3233, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка</div>
  <div data-layer="допечатка" style={{left: 1182, top: 3233, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>допечатка</div>
  <div data-layer="тренд" style={{left: 1452, top: 3233, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>тренд</div>
  <div data-layer="обучение" style={{left: 1674, top: 3233, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>обучение</div>
  <div data-layer="имя" style={{left: 928, top: 1278, position: 'absolute', textAlign: 'center', color: '#979797', fontSize: 32, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>имя</div>
  <div data-layer="Портфолио" style={{width: 1774, height: 123, left: 73, top: 419, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 128, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>Портфолио</div>
  <div data-layer="сайт" style={{width: 1774, height: 44, left: 73, top: 385, position: 'absolute', textAlign: 'center', color: '#AAAAAA', fontSize: 36, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>сайт</div>
  <div data-layer="не виртуального дизайнер" style={{width: 1774, height: 44, left: 73, top: 581, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 36, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>не виртуального дизайнер</div>
  <img data-layer="117928672_196663831878394_6093360682293770305_n" className="1966638318783946093360682293770305N" style={{width: 350, height: 350, left: 779, top: 874, position: 'absolute', borderRadius: 175}} src="https://placehold.co/350x350" />
  <div data-layer="17" style={{width: 124, left: 237, top: 1778, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 128, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>17 </div>
  <div data-layer="0" style={{width: 115, height: 145, left: 991, top: 1808, position: 'absolute', color: 'black', fontSize: 160, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>0</div>
  <div data-layer="2000" style={{width: 333, height: 118, left: 514, top: 1835, position: 'absolute', color: 'black', fontSize: 128, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'capitalize', wordWrap: 'break-word'}}>2000</div>
  <div data-layer="лет" style={{width: 130, height: 60, left: 235, top: 1893, position: 'absolute', color: 'black', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>лет</div>
  <div data-layer="до выхода продукта на рынок" style={{width: 209, height: 107, left: 1107, top: 1857, position: 'absolute', color: 'black', fontSize: 30, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>до выхода продукта <br/>на рынок</div>
  <div data-layer="руководства управление обучение" style={{left: 1449, top: 1857, position: 'absolute', color: 'black', fontSize: 30, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>руководства<br/>управление<br/>обучение</div>
  <div data-layer="более" style={{left: 514, top: 1788, position: 'absolute', color: 'black', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>более</div>
  <div data-layer="неприрывный стаж работы" style={{left: 235, top: 1736, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'lowercase', wordWrap: 'break-word'}}>неприрывный <br/>стаж работы</div>
  <div data-layer="разработка полной стилистики бренда с" style={{width: 244, height: 47, left: 991, top: 1736, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'lowercase', wordWrap: 'break-word'}}>разработка полной стилистики бренда с</div>
  <div data-layer="дополнительный опыт" style={{width: 197, left: 1449, top: 1736, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'lowercase', wordWrap: 'break-word'}}>дополнительный опыт</div>
  <div data-layer="разработано и реализовано макетов" style={{width: 359, height: 52, left: 512, top: 1736, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'lowercase', wordWrap: 'break-word'}}>разработано и реализовано макетов</div>
  <div data-layer="Line 1" className="Line1" style={{width: 180, height: 0, left: 440, top: 1758, position: 'absolute', transform: 'rotate(90deg)', transformOrigin: 'top left', outline: '1px black solid', outlineOffset: '-0.50px'}}></div>
  <div data-layer="Line 2" className="Line2" style={{width: 180, height: 0, left: 919, top: 1758, position: 'absolute', transform: 'rotate(90deg)', transformOrigin: 'top left', outline: '1px black solid', outlineOffset: '-0.50px'}}></div>
  <div data-layer="Line 3" className="Line3" style={{width: 180, height: 0, left: 1377, top: 1758, position: 'absolute', transform: 'rotate(90deg)', transformOrigin: 'top left', outline: '1px black solid', outlineOffset: '-0.50px'}}></div>
  <div data-layer="Frame 2" className="Frame2" style={{width: 1920, height: 950, left: 0, top: 2070, position: 'absolute'}}>
    <div data-layer="Rectangle 4" className="Rectangle4" style={{width: 1920, height: 950, left: 0, top: 0, position: 'absolute', background: 'black'}} />
    <div data-layer="направление" style={{width: 792, height: 285, left: 104, top: 214, position: 'absolute', textAlign: 'right', color: '#505050', fontSize: 96, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>направление</div>
    <div data-layer="веб дизайн полиграфия графический дизайн наружная реклама ретушь" style={{width: 865, left: 31, top: 357, position: 'absolute', textAlign: 'right', color: '#8F8F8F', fontSize: 65, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>веб дизайн<br/>полиграфия<br/>графический дизайн<br/>наружная реклама<br/>ретушь</div>
    <img data-layer="171941-black-folders-mockup-opened-and-closed (1) 1" className="BlackFoldersMockupOpenedAndClosed11" style={{width: 961.50, height: 950, left: 957, top: 0, position: 'absolute', mixBlendMode: 'luminosity'}} src="https://placehold.co/961x950" />
    <div data-layer="Line 4" className="Line4" style={{width: 150, height: 0, left: 807, top: 338, position: 'absolute', outline: '5px white solid', outlineOffset: '-2.50px'}}></div>
    <div data-layer="Rectangle 5" className="Rectangle5" style={{width: 15, height: 15, left: 881, top: 759, position: 'absolute', background: 'white'}} />
  </div>
  <div data-layer="Rectangle 6" className="Rectangle6" style={{width: 11, height: 11, left: 147, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 12" className="Rectangle12" style={{width: 11, height: 11, left: 451, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 18" className="Rectangle18" style={{width: 11, height: 11, left: 682, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 24" className="Rectangle24" style={{width: 11, height: 11, left: 940, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 30" className="Rectangle30" style={{width: 11, height: 11, left: 1182, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 36" className="Rectangle36" style={{width: 11, height: 11, left: 1452, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 42" className="Rectangle42" style={{width: 11, height: 11, left: 1674, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 7" className="Rectangle7" style={{width: 11, height: 11, left: 164, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 13" className="Rectangle13" style={{width: 11, height: 11, left: 468, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 19" className="Rectangle19" style={{width: 11, height: 11, left: 699, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 25" className="Rectangle25" style={{width: 11, height: 11, left: 957, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 31" className="Rectangle31" style={{width: 11, height: 11, left: 1199, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 37" className="Rectangle37" style={{width: 11, height: 11, left: 1469, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 43" className="Rectangle43" style={{width: 11, height: 11, left: 1691, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 8" className="Rectangle8" style={{width: 11, height: 11, left: 181, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 14" className="Rectangle14" style={{width: 11, height: 11, left: 485, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 20" className="Rectangle20" style={{width: 11, height: 11, left: 716, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 26" className="Rectangle26" style={{width: 11, height: 11, left: 974, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 32" className="Rectangle32" style={{width: 11, height: 11, left: 1216, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 38" className="Rectangle38" style={{width: 11, height: 11, left: 1486, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 44" className="Rectangle44" style={{width: 11, height: 11, left: 1708, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 9" className="Rectangle9" style={{width: 11, height: 11, left: 198, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 15" className="Rectangle15" style={{width: 11, height: 11, left: 502, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 21" className="Rectangle21" style={{width: 11, height: 11, left: 733, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 27" className="Rectangle27" style={{width: 11, height: 11, left: 991, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 33" className="Rectangle33" style={{width: 11, height: 11, left: 1233, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 39" className="Rectangle39" style={{width: 11, height: 11, left: 1503, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 45" className="Rectangle45" style={{width: 11, height: 11, left: 1725, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 10" className="Rectangle10" style={{width: 11, height: 11, left: 215, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 16" className="Rectangle16" style={{width: 11, height: 11, left: 519, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 22" className="Rectangle22" style={{width: 11, height: 11, left: 750, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 28" className="Rectangle28" style={{width: 11, height: 11, left: 1008, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 34" className="Rectangle34" style={{width: 11, height: 11, left: 1250, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 40" className="Rectangle40" style={{width: 11, height: 11, left: 1520, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 46" className="Rectangle46" style={{width: 11, height: 11, left: 1742, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 11" className="Rectangle11" style={{width: 11, height: 11, left: 232, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 17" className="Rectangle17" style={{width: 11, height: 11, left: 536, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 23" className="Rectangle23" style={{width: 11, height: 11, left: 767, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 29" className="Rectangle29" style={{width: 11, height: 11, left: 1025, top: 3341, position: 'absolute', background: 'black', borderRadius: 50}} />
  <div data-layer="Rectangle 35" className="Rectangle35" style={{width: 11, height: 11, left: 1267, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 41" className="Rectangle41" style={{width: 11, height: 11, left: 1537, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 47" className="Rectangle47" style={{width: 11, height: 11, left: 1759, top: 3341, position: 'absolute', background: '#AAAAAA', borderRadius: 50}} />
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 693, top: 4191, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 959, top: 4218, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 1019, top: 4257, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 743, top: 4386, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 726, top: 4571, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 726, top: 4604, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 726, top: 4667, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 1100, top: 4667, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 73, top: 4191, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 339, top: 4218, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 399, top: 4257, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 123, top: 4386, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 106, top: 4571, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 106, top: 4604, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 106, top: 4667, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 480, top: 4667, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 1313, top: 4191, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 1579, top: 4218, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 1639, top: 4257, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 1363, top: 4386, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 1346, top: 4571, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 1346, top: 4604, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 1346, top: 4667, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 1720, top: 4667, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 693, top: 4811, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 959, top: 4838, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 1019, top: 4877, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 743, top: 5006, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 726, top: 5191, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 726, top: 5224, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 726, top: 5287, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 1100, top: 5287, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 1313, top: 4811, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 1579, top: 4838, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 1639, top: 4877, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 1363, top: 5006, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 1346, top: 5191, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 1346, top: 5224, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 1346, top: 5287, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 1720, top: 5287, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 693, top: 5431, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 959, top: 5458, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 1019, top: 5497, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 743, top: 5626, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 726, top: 5811, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 726, top: 5844, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 726, top: 5907, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 1100, top: 5907, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 57" className="Rectangle57" style={{width: 530, height: 530, left: 1313, top: 5431, position: 'absolute', background: 'white', border: '1px black solid'}} />
  <div data-layer="Rectangle 60" className="Rectangle60" style={{width: 215, height: 125, left: 1579, top: 5458, position: 'absolute', background: '#D9D9D9'}} />
  <div data-layer="лого 215x125" className="215x125" style={{width: 96, height: 48, left: 1639, top: 5497, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>лого <br/>215x125</div>
  <div data-layer="название компании" style={{left: 1363, top: 5626, position: 'absolute', textBoxTrim: 'trim-both', textBoxEdge: 'cap alphabetic', textAlign: 'right', color: 'black', fontSize: 72, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>название<br/>компании</div>
  <div data-layer="разработка:" style={{left: 1346, top: 5811, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>разработка:</div>
  <div data-layer="верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати" style={{width: 448, height: 54, left: 1346, top: 5844, position: 'absolute', color: '#AAAAAA', fontSize: 13, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>верстка, дизайн, рекламные макеты, допечатная подготовка, ретушь, цветокоррекция, сопровождение печати</div>
  <div data-layer="сайт компании" style={{left: 1346, top: 5907, position: 'absolute', color: 'black', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>сайт компании</div>
  <div data-layer="#категория" style={{left: 1720, top: 5907, position: 'absolute', textAlign: 'right', color: '#AAAAAA', fontSize: 16, fontFamily: 'Russo One', fontWeight: '400', wordWrap: 'break-word'}}>#категория</div>
  <div data-layer="Rectangle 53" className="Rectangle53" style={{width: 109, height: 16, left: 1811, top: 4056, position: 'absolute', background: '#505050'}} />
  <div data-layer="Rectangle 56" className="Rectangle56" style={{width: 125, height: 6, left: 891, top: 1409, position: 'absolute', background: 'black'}} />
  <div data-layer="Rectangle 59" className="Rectangle59" style={{width: 44, height: 243, left: 1876, top: 1356, position: 'absolute', background: 'black'}} />
  <div data-layer="идеология" style={{width: 193, height: 22, left: 1881, top: 1574, position: 'absolute', transform: 'rotate(-90deg)', transformOrigin: 'top left', color: 'white', fontSize: 30, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>идеология</div>
  <div data-layer="+7 (928) 418-35-37" className="79284183537" style={{left: 1076, top: 7250, position: 'absolute', color: 'white', fontSize: 64, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>+7 (928) 418-35-37</div>
  <div data-layer="мессенджеры" style={{left: 1076, top: 7385, position: 'absolute', color: '#AAAAAA', fontSize: 36, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>мессенджеры</div>
  <div data-layer="Готов к сотрудничеству" style={{left: 1076, top: 7117, position: 'absolute', color: 'white', fontSize: 36, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>Готов к сотрудничеству</div>
  <div data-layer="почта" style={{left: 1076, top: 7486, position: 'absolute', color: '#AAAAAA', fontSize: 36, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>почта</div>
  <div data-layer="Rectangle 5" className="Rectangle5" style={{width: 15, height: 15, left: 1076, top: 7449, position: 'absolute', background: 'white'}} />
  <div data-layer="контакты" style={{left: 1265, top: 6731, position: 'absolute', textAlign: 'right', color: 'white', fontSize: 96, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>контакты</div>
  <div data-layer="Rectangle 54" className="Rectangle54" style={{width: 109, height: 16, left: 1811, top: 6804, position: 'absolute', background: 'white'}} />
  <div data-layer="меню" style={{width: 398, height: 28, left: 1447, top: 39, position: 'absolute'}}>
    <div data-layer="Rectangle 54" className="Rectangle54" style={{width: 398, height: 28, left: 0, top: 0, position: 'absolute', background: 'white'}} />
    <div data-layer="био" style={{left: 19, top: 6, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 14, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>био</div>
    <div data-layer="контакты" style={{left: 301, top: 6, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 14, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>контакты</div>
    <div data-layer="направление" style={{left: 80, top: 6, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 14, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>направление</div>
    <div data-layer="кейсы" style={{left: 219, top: 6, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 14, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>кейсы</div>
  </div>
  <div data-layer="меню" style={{width: 164, height: 28, left: 74, top: 39, position: 'absolute'}}>
    <div data-layer="Rectangle 54" className="Rectangle54" style={{width: 164, height: 28, left: 0, top: 0, position: 'absolute', background: 'white'}} />
    <div data-layer="био" style={{left: 7.83, top: 6, position: 'absolute', color: 'black', fontSize: 14, fontFamily: 'Russo One', fontWeight: '400', textTransform: 'uppercase', wordWrap: 'break-word'}}>михаил образцов</div>
  </div>
</div>